---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@ce9a118b05e90e186dba48a82067adeed185f7d4
        with:
          devshell: ci
          skip-build: "true"
          accept-flake-config: "true"
          cachix-cache: pr0d1r2
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build CV and verify content not stale
        run: |
          nix develop .#ci --accept-flake-config --command bash scripts/build.sh
          nix develop .#ci --accept-flake-config --command bash -c \
            'pdftotext -layout cv.pdf - | diff - cv.txt'

  check-darwin:
    needs: check-linux
    runs-on: macos-latest
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@ce9a118b05e90e186dba48a82067adeed185f7d4
        with:
          devshell: ci
          skip-build: "true"
          skip-lefthook: "true"
          accept-flake-config: "true"
          cachix-cache: pr0d1r2
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build CV on macOS
        run: nix develop .#ci --accept-flake-config --command bash scripts/build.sh
